apiVersion: v1
kind: Service
metadata:
  name: localizacao-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"  
spec:
  selector:
    app: localizacao-service
  ports:
    - protocol: TCP
      port: 80  # Porta externa (externamente será a porta do NodePort)
      targetPort: 8080  # Porta interna do container da API
      nodePort: 30004  # Definindo manualmente uma porta entre 30000-32767
  type: NodePort  # Expor o serviço fora do cluster
