apiVersion: apps/v1
kind: Deployment
metadata:
  name: localizacao-service
  annotations:
    app.kubernetes.io/version: "1.2.0"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    description: "API com os endpoint responsáveis para realizar o mapeamento dos DDD existem no Brasil, com as suas respectivas regiões."  
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: localizacao-service
  template:
    metadata:
      labels:
        app: localizacao-service
    spec:
      containers:
      - name: localizacao-service
        image: netiim/localizacao-service:8
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: connection-strings-secrets
        
        

