apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  annotations:
    description: "StatefulSet para armazenamento persistente do RabbitMq"
spec:
  serviceName: "rabbitmq"
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: netiim/rabbitmq:1
        envFrom:
        - configMapRef:
            name: rabbitmq-config
        ports:
        - containerPort: 5672  # Porta do RabbitMQ para comunicação AMQP
        - containerPort: 15672  # Porta de administração do RabbitMQ
        - containerPort: 15692 # Porta para o endpoint de métricas do Prometheus
        livenessProbe:
          tcpSocket:
            port: 5672                   
          initialDelaySeconds: 30             
          periodSeconds: 10                   
          failureThreshold: 3     
        readinessProbe:
          tcpSocket:
            port: 5672                     
          initialDelaySeconds: 5              
          periodSeconds: 10                   
          failureThreshold: 5                 

        volumeMounts:
        - name: rabbitmq-persistent-storage
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-persistent-storage
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
