apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-pvc
  annotations:
    description: "PVC para armazenamento persistente do SqlServer"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
