apiVersion: v1
kind: Service
metadata:
  name: sql-server-svc
  annotations:
    prometheus.io/scrape: "false" 
spec:
  selector:
    app: sql-server
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
    nodePort: 31367
  type: NodePort