apiVersion: apps/v1
kind: Deployment
metadata:
  name: contato-service
  annotations:
    app.kubernetes.io/version: "1.2.0"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    description: "API com os endpoint responsáveis para cadastrar contatos"
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: contato-service
  template:
    metadata:
      labels:
        app: contato-service
    spec:
      containers:
      - name: contato-service
        image: netiim/api-tech-challenge:18
        ports:
        - containerPort: 8080 
        envFrom:
        - secretRef:
            name: connection-strings-secrets
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
