apiVersion: v1
kind: Service
metadata:
  name: contato-service
spec:
  selector:
    app: contato-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30005
  type: NodePort
