apiVersion: v1
kind: Service
metadata:
  name: contato-get-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "30006"
spec:
  selector:
    app: contato-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30005
  type: NodePort
