apiVersion: apps/v1
kind: Deployment
metadata:
  name: contato-post-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contato-post-worker
  template:
    metadata:
      labels:
        app: contato-post-worker
    spec:
      containers:
        - name: contato-post
          image: netiim/contato-post:11
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
