apiVersion: apps/v1
kind: Deployment
metadata:
  name: contato-get-worker
  annotations:
    app.kubernetes.io/version: "1.2.0"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    description: "Worker responsável por processar mensagens de fila"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contato-get-worker
  template:
    metadata:
      labels:
        app: contato-get-worker
    spec:
      containers:
        - name: contato-get
          image: netiim/contato-get:10
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
              name: connection-strings-secrets                 
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
