apiVersion: apps/v1
kind: Deployment
metadata:
  name: contato-delete-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contato-delete-worker
  template:
    metadata:
      labels:
        app: contato-delete-worker
    spec:
      containers:
        - name: contato-delete
          image: netiim/contato-delete:6
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
