apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler  
metadata:  
  name: contato-delete-worker-hpa  
  annotations:
    description: "HPA para escalar o worker de processamento de mensagens da fila"
spec:  
  scaleTargetRef:  
    apiVersion: apps/v1  
    kind: Deployment  
    name: contato-delete-worker
  minReplicas: 1  
  maxReplicas: 10  
  metrics:  
    - type: Resource  
      resource:  
        name: cpu  
        target:  
          type: Utilization  
          averageUtilization: 50