apiVersion: apps/v1
kind: Deployment
metadata:
  name: contato-get-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contato-get-worker
  template:
    metadata:
      labels:
        app: contato-get-worker
    spec:
      containers:
        - name: contato-get
          image: netiim/contato-get:6
          ports:
            - containerPort: 8080
          resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"



