apiVersion: v1
kind: Service
metadata:
  name: worker-update-service
spec:
  selector:
    app: contato-update-worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP