apiVersion: apps/v1
kind: Deployment
metadata:
  name: contato-delete-worker
  annotations:
    app.kubernetes.io/version: "1.2.0"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    description: "Worker responsável por processar mensagens de fila"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contato-delete-worker
  template:
    metadata:
      labels:
        app: contato-delete-worker
    spec:
      containers:
        - name: contato-delete
          image: netiim/contato-delete:8
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
              name: connection-strings-secrets 
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
