apiVersion: v1
kind: Service
metadata:
  name: worker-update-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "30006"
spec:
  selector:
    app: contato-update-worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP