apiVersion: v1
kind: Service
metadata:
  name: worker-post-service
spec:
  selector:
    app: contato-post-worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP