apiVersion: apps/v1
kind: Deployment
metadata:
  name: contato-update-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contato-update-worker
  template:
    metadata:
      labels:
        app: contato-update-worker
    spec:
      containers:
        - name: contato-update
          image: netiim/contato-put:10
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
