apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  annotations:
    description: "StatefulSet para armazenamento persistente do MongoDb"
spec:
  serviceName: "mongo"
  replicas: 1  
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        livenessProbe:
          tcpSocket:
            port: 27017  
          initialDelaySeconds: 30  
          periodSeconds: 10        
          failureThreshold: 3   
        readinessProbe:
          tcpSocket:
            port: 27017  
          initialDelaySeconds: 5   
          periodSeconds: 10        
          failureThreshold: 5      
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db  # Onde os dados do MongoDB serão armazenados
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc  # Referenciando o PVC existente