apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  annotations:
    prometheus.io/scrape: "false" 
spec:
  ports:
    - port: 27017
  clusterIP: None  # Headless Service
  selector:
    app: mongo